t

diff --git a/.github/workflows/lint-and-format.yaml b/.github/workflows/lint-and-format.yaml
--- a/.github/workflows/lint-and-format.yaml
+++ b/.github/workflows/lint-and-format.yaml
@@ -1,11 +1,8 @@
 name: Lint and Format
 
 on:
-  # pull_request:
-  #   branches:
-  #     - main
   pull_request:
-    types: [closed]
+    types: [opened, reopened, synchronize]
     branches:
       - main
 
@@ -21,13 +18,6 @@ jobs:
         uses: actions/setup-node@v3
         with:
           node-version: '16'
-      
-      - name: Pull latest changes
-        if: steps.check_dir.outputs.exists == 'true'
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        run: |
-          git pull origin main
 
       - name: Check if main-dev directory exists
         id: check_dir
@@ -39,7 +29,14 @@ jobs:
             echo "main-dev directory not found"
             echo "::set-output name=exists::false"
           fi
-        
+
+      - name: Pull latest changes
+        if: steps.check_dir.outputs.exists == 'true'
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          git pull origin ${{ github.head_ref }}
+
       - name: Install dependencies
         if: steps.check_dir.outputs.exists == 'true'
         run: |
@@ -53,22 +50,29 @@ jobs:
           npm run lint
         continue-on-error: true
 
-      - name: Run Prettier
+      - name: Run Prettier Check
+        id: prettier_check
         if: steps.check_dir.outputs.exists == 'true'
+        run: |
+          cd applications/frontends/main-dev
+          npm run prettier:check
+
+      - name: Run Prettier Fix
+        if: failure() && steps.check_dir.outputs.exists == 'true'
         run: |
           cd applications/frontends/main-dev
           npm run format
         continue-on-error: true
 
       - name: Commit changes
-        if: steps.check_dir.outputs.exists == 'true'
+        if: failure() && steps.check_dir.outputs.exists == 'true'
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           cd applications/frontends/main-dev
           git config --global user.name 'github-actions[bot]'
           git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
           git add .
           git commit -m 'Apply ESLint and Prettier fixes' || echo 'No changes to commit'
-          git pull --rebase origin main || (echo "Rebase failed due to conflicts" && exit 1)
-          git push origin HEAD:main
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          git pull --rebase origin ${{ github.head_ref }} || (echo "Rebase failed due to conflicts" && exit 1)
+          git push origin HEAD:${{ github.head_ref }}
