g

diff --git a/.github/workflows/lint-and-format.yaml b/.github/workflows/lint-and-format.yaml
--- a/.github/workflows/lint-and-format.yaml
+++ b/.github/workflows/lint-and-format.yaml
@@ -48,18 +48,17 @@ jobs:
         if: steps.check_dir.outputs.exists == 'true'
         run: |
           cd applications/frontends/main-dev
-          npm run prettier:check
-        continue-on-error: true
+          npm run prettier:check || echo "Prettier check failed" && exit 1
 
       - name: Run Prettier Fix
-        if: steps.prettier_check.conclusion == 'failure' && steps.check_dir.outputs.exists == 'true'
+        if: always() && steps.prettier_check.outcome == 'failure' && steps.check_dir.outputs.exists == 'true'
         run: |
           cd applications/frontends/main-dev
           npm run format
         continue-on-error: true
 
       - name: Commit changes
-        if: steps.prettier_check.conclusion == 'failure' && steps.check_dir.outputs.exists == 'true'
+        if: always() && steps.prettier_check.outcome == 'failure' && steps.check_dir.outputs.exists == 'true'
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
